services:
  sazare:
    image: ghcr.io/fu-foo/fhir-sazare:latest
    # To build locally instead: comment out 'image' and uncomment 'build'
    # build: .
    ports:
      - "8080:8080"
    volumes:
      - sazare-data:/data
      - ./config.yaml:/etc/sazare/config.yaml:ro
    environment:
      - SAZARE_DATA_DIR=/data
      - RUST_LOG=info

volumes:
  sazare-data:
